"""Agregar recibido por vendedor.

Revision ID: 7326b31cb4e4
Revises: d045181d4db0
Create Date: 2026-03-29 14:50:16.124655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7326b31cb4e4'
down_revision = 'd045181d4db0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('solicitudes_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recibido_por_vendedor', sa.Boolean(), nullable=True))

    op.execute(
        "UPDATE solicitudes_stock SET recibido_por_vendedor = false WHERE recibido_por_vendedor IS NULL"
    )

    with op.batch_alter_table('solicitudes_stock', schema=None) as batch_op:
        batch_op.alter_column(
            'recibido_por_vendedor',
            existing_type=sa.Boolean(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_stock', schema=None) as batch_op:
        batch_op.drop_column('recibido_por_vendedor')

    # ### end Alembic commands ###
